<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 site-animation.glb
-->

<script lang="ts">
	import {
		AnimationAction,
		Color,
		Group,
		LoopOnce,
		Material,
		Mesh,
		MeshBasicMaterial,
		MeshStandardMaterial,
		MirroredRepeatWrapping,
		TextureLoader,
		Vector2
	} from 'three';
	import { T, useTask } from '@threlte/core';
	import { interactivity, Text, useCursor, useGltf, useGltfAnimations } from '@threlte/extras';
	import SiteAnimation from '$lib/assets/gltf/site-animation.glb';
	import WorldReverseImage from '$lib/assets/images/WorldReverseGreen.png';
	import FloorTexture from '$lib/assets/images/Grid.png';
	import { Spring, Tween } from 'svelte/motion';

	let { fallback, error, children, ref = $bindable(), ...props } = $props();
	ref = new Group();
	const gltf = useGltf<{
		nodes: Record<string, Mesh>;
		materials: Record<string, Material>;
	}>(SiteAnimation as string);
	export const { actions, mixer } = useGltfAnimations(gltf, ref);
	const showText = false;

	interactivity();

	const { onPointerEnter, onPointerLeave } = useCursor();

	let started = $state(false);

	const sphereProps = {
		Sphere01: createSphere(),
		Sphere02: createSphere(),
		Sphere03: createSphere(),
		Sphere04: createSphere(),
		Sphere05: createSphere(),
		Sphere06: createSphere(),
		Sphere07: createSphere()
	} as const;

	const cameraZoom = new Tween(200);
	const enterTextOpacity = new Tween(1);
	const wireframeMaterial = createWorldTexture();
	const floorMaterial = createFloorMaterial();

	let sphereRotation = $state(0);

	sphereProps.Sphere01.onClick = () => {
		constalationAnimation();
		sphereProps.Sphere01.onClick = () => console.log('sphere 1 clicked');
	};

	function createSphere() {
		const scale = new Spring(1);
		return {
			scale,
			onHover: () => {
				onPointerEnter();
				if (started === false) return;
				scale.set(1.2);
			},
			onHoverLeave: () => {
				onPointerLeave();
				if (started === false) return;
				scale.set(1);
			},
			onClick: () => {
				if (started === false) return;
				console.log('sphere clicked');
			}
		};
	}

	function constalationAnimation() {
		console.log('actions', $actions);
		started = true;
		animateOnce($actions['CameraAction']);
		cameraZoom.set(80);
		enterTextOpacity.set(0);
		Object.entries($actions)
			.filter(([name, _action]) => name.includes('Move'))
			.forEach(([_, action]) => animateOnce(action));
	}

	function animateOnce(action: AnimationAction | undefined) {
		if (!action) return;
		action.clampWhenFinished = true;
		action.setLoop(LoopOnce, 1).play();
	}

	function createWorldTexture() {
		const material = new MeshStandardMaterial();
		const worldTexture = new TextureLoader().load(WorldReverseImage);
		worldTexture.flipY = false;
		material.color = new Color().setRGB(0, 0, 0);
		material.emissiveMap = worldTexture;
		material.emissive = new Color().setRGB(255, 255, 255);
		material.emissiveIntensity = 0.01;
		return material;
	}

	useTask((delta) => {
		sphereRotation += delta * 0.5;
	});

	function createFloorMaterial() {
		const material = new MeshBasicMaterial();
		const planeTexture = new TextureLoader().load(FloorTexture);
		const vectorValue = 7;
		planeTexture.repeat = new Vector2(vectorValue, vectorValue);
		planeTexture.wrapS = planeTexture.wrapT = MirroredRepeatWrapping;
		material.map = planeTexture;
		material.opacity = 0.2;
		material.transparent = true;
		return material;
	}

  function degreeToRadian(degree: number) {
    return degree * (Math.PI / 180);
  } 
</script>

<T is={ref} dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group name="Scene">
			<T.OrthographicCamera
				name="Camera01"
				makeDefault={true}
				zoom={cameraZoom.current}
				far={100}
				near={0.1}
				position={[7.07, 1, 7.06]}
				rotation={[0, Math.PI / 4, 0]}
			/>
			<T.DirectionalLight
				name="Sun"
				intensity={1}
				decay={2}
				position={[0, 21.62, 0]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<T.Mesh
				name="Plane"
				geometry={gltf.nodes.Plane.geometry}
				material={floorMaterial}
				scale={58.28}
			/>
			<T.Mesh
				name="Sphere01"
				geometry={gltf.nodes.Sphere01.geometry}
				material={wireframeMaterial}
				position={[0, 1, 0]}
				rotation.y={sphereRotation}
				scale={sphereProps.Sphere01.scale.current}
				onpointerenter={sphereProps.Sphere01.onHover}
				onpointerleave={sphereProps.Sphere01.onHoverLeave}
				onclick={sphereProps.Sphere01.onClick}
			/>
			<T.Mesh
				name="Sphere02"
				geometry={gltf.nodes.Sphere02.geometry}
				material={wireframeMaterial}
				position={[0, 1, 0]}
				rotation.y={sphereRotation}
				scale={sphereProps.Sphere01.scale.current}
				onpointerenter={sphereProps.Sphere01.onHover}
				onpointerleave={sphereProps.Sphere01.onHoverLeave}
				onclick={sphereProps.Sphere01.onClick}
			/>
			<T.Mesh
				name="Sphere03"
				geometry={gltf.nodes.Sphere03.geometry}
				material={wireframeMaterial}
				position={[0, 1, 0]}
				rotation.y={sphereRotation}
				scale={sphereProps.Sphere01.scale.current}
				onpointerenter={sphereProps.Sphere01.onHover}
				onpointerleave={sphereProps.Sphere01.onHoverLeave}
				onclick={sphereProps.Sphere01.onClick}
			/>
			<T.Mesh
				name="Sphere04"
				geometry={gltf.nodes.Sphere04.geometry}
				material={wireframeMaterial}
				position={[0, 1, 0]}
				rotation.y={sphereRotation}
				scale={sphereProps.Sphere01.scale.current}
				onpointerenter={sphereProps.Sphere01.onHover}
				onpointerleave={sphereProps.Sphere01.onHoverLeave}
				onclick={sphereProps.Sphere01.onClick}
			/>
			<T.Mesh
				name="Sphere05"
				geometry={gltf.nodes.Sphere05.geometry}
				material={wireframeMaterial}
				position={[0, 1, 0]}
				rotation.y={sphereRotation}
				scale={sphereProps.Sphere01.scale.current}
				onpointerenter={sphereProps.Sphere01.onHover}
				onpointerleave={sphereProps.Sphere01.onHoverLeave}
				onclick={sphereProps.Sphere01.onClick}
			/>
			<T.Mesh
				name="Sphere06"
				geometry={gltf.nodes.Sphere06.geometry}
				material={wireframeMaterial}
				position={[0, 1, 0]}
				rotation.y={sphereRotation}
				scale={sphereProps.Sphere01.scale.current}
				onpointerenter={sphereProps.Sphere01.onHover}
				onpointerleave={sphereProps.Sphere01.onHoverLeave}
				onclick={sphereProps.Sphere01.onClick}
			/>
			<T.Mesh
				name="Sphere07"
				geometry={gltf.nodes.Sphere07.geometry}
				material={wireframeMaterial}
				position={[0, 1, 0]}
				rotation.y={sphereRotation}
				scale={sphereProps.Sphere01.scale.current}
				onpointerenter={sphereProps.Sphere01.onHover}
				onpointerleave={sphereProps.Sphere01.onHoverLeave}
				onclick={sphereProps.Sphere01.onClick}
			/>
			<T.Mesh
				name="Torus01"
				geometry={gltf.nodes.Torus01.geometry}
				material={gltf.materials['Torus.001']}
				position={[0, 0.01, 0]}
				scale={0.96}
			/>
			<T.Mesh
				name="Torus02"
				geometry={gltf.nodes.Torus02.geometry}
				material={gltf.materials.Torus}
				position={[0, 0.01, 0]}
				scale={0.96}
			/>
			<T.Mesh
				name="Torus03"
				geometry={gltf.nodes.Torus03.geometry}
				material={gltf.materials.Torus}
				position={[0, 0.01, 0]}
				scale={0.96}
			/>
			<T.Mesh
				name="Torus04"
				geometry={gltf.nodes.Torus04.geometry}
				material={gltf.materials.Torus}
				position={[0, 0.01, 0]}
				scale={0.96}
			/>
			<T.Mesh
				name="Torus05"
				geometry={gltf.nodes.Torus05.geometry}
				material={gltf.materials.Torus}
				position={[0, 0.01, 0]}
				scale={0.96}
			/>
			<T.Mesh
				name="Torus06"
				geometry={gltf.nodes.Torus06.geometry}
				material={gltf.materials.Torus}
				position={[0, 0.01, 0]}
				scale={0.96}
			/>
			<T.Mesh
				name="Torus07"
				geometry={gltf.nodes.Torus07.geometry}
				material={gltf.materials.Torus}
				position={[0, 0.01, 0]}
				scale={0.96}
			/>
			<T.Mesh
				name="Sphere08"
				geometry={gltf.nodes.Sphere08.geometry}
				material={wireframeMaterial}
				position={[0, 1, 0]}
				rotation.y={sphereRotation}
			/>
			<T.Mesh
				name="Sphere09"
				geometry={gltf.nodes.Sphere09.geometry}
				material={wireframeMaterial}
				position={[0, 1, 0]}
				rotation.y={sphereRotation}
			/>
			<T.Mesh
				name="Sphere10"
				geometry={gltf.nodes.Sphere10.geometry}
				material={wireframeMaterial}
				position={[0, 1, 0]}
				rotation.y={sphereRotation}
			/>
			<T.Mesh
				name="Sphere11"
				geometry={gltf.nodes.Sphere11.geometry}
				material={wireframeMaterial}
				position={[0, 1, 0]}
				rotation.y={sphereRotation}
			/>
			<T.Mesh
				name="Sphere12"
				geometry={gltf.nodes.Sphere12.geometry}
				material={wireframeMaterial}
				position={[0, 1, 0]}
				rotation.y={sphereRotation}
			/>
			<T.Mesh
				name="Sphere13"
				geometry={gltf.nodes.Sphere13.geometry}
				material={wireframeMaterial}
				position={[0, 1, 0]}
				rotation.y={sphereRotation}
			/>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T>
