<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 ./site-animation.glb
-->

<script lang="ts">
  import { AnimationAction, Group, LoopOnce, Material, Mesh } from 'three'
  import { T } from '@threlte/core'
  import { interactivity, useGltf, useGltfAnimations } from '@threlte/extras'
  import SiteAnimation from '$lib/assets/gltf/site-animation.glb'
	import { Spring } from 'svelte/motion';

  let { fallback, error, children, ref = $bindable(), ...props} = $props()
  ref = new Group()
  const gltf = useGltf<{
    nodes: Record<string, Mesh>,
    materials: Record<string, Material>
  }>(SiteAnimation as string)
  export const { actions, mixer } = useGltfAnimations(gltf, ref);

  interactivity();

  let started = $state(false);
	const sphereProps = {
		Sphere01: createSphere(),
		Sphere02: createSphere(),
		Sphere03: createSphere(),
		Sphere04: createSphere(),
		Sphere05: createSphere(),
		Sphere06: createSphere(),
		Sphere07: createSphere(),
	} as const;

	sphereProps.Sphere01.onClick = () => {
		start();
		sphereProps.Sphere01.onClick = () => console.log('sphere 1 clicked');
	};

	function createSphere( ) {
		const scale = new Spring(1);
		return {
			scale,
			onHover: () => {
        if(started === false) return;
        scale.set(1.2);
      },
			onHoverLeave: ()=> {
        if(started === false) return;
        scale.set(1);
      },
			onClick: ()=>{
        if(started === false) return;
        console.log('sphere clicked')
      },
		}
	}

	function start() {
		console.log('actions', $actions);
    started = true;
		animateOnce($actions['CameraAction']);
    Object.entries($actions)
    .map(entry=>{
      console.log('entry', entry);
      return entry;
    })
    .filter(([name, _action]) => name.includes('Move'))
    .forEach(([_, action]) => animateOnce(action));
	}

	function animateOnce(action: AnimationAction | undefined) {
		if (!action) return;
		action.clampWhenFinished = true;
		action.setLoop(LoopOnce, 1).play();
	}

//   spinSpheres();

//  function spinSpheres() {
//     const sphereGroup = createSphereGroup();
//     if(!sphereGroup) return;
//     const clip = $actions['Spin']?.getClip();
//     if(!clip) return;
//     const spinAction = mixer.clipAction(clip, sphereGroup);
//     spinAction.play();
//   }

//   function createSphereGroup() {
//     const nodes = $gltf?.nodes;
//     if(!nodes) return null;
//     const Objects = Object.entries($gltf?.nodes)
//       .filter(([name, Object3D]) => name.includes('Sphere'))
//       .map(([_name, Object3D]) => {
//         Object3D.rotation.set(0, 0, 0);
//         return Object3D;
//     });
//     return new AnimationObjectGroup(...Objects);
//   }
</script>

<T
  is={ref}
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Scene">
      <T.PerspectiveCamera
        name="Camera"
        makeDefault={true}
        far={100}
        near={0.1}
        fov={22.9}
        position={[7.07, 1, 7.06]}
        rotation={[0, Math.PI / 4, 0]}
      />
      <T.DirectionalLight
        name="Sun"
        intensity={1}
        decay={2}
        position={[0, 21.62, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <T.Group position={[0, 0, -1]} />
      </T.DirectionalLight>
      <T.Mesh
        name="Sphere01"
        geometry={gltf.nodes.Sphere01.geometry}
        material={gltf.materials.Wireframe}
        position={[0, 1, 0]}
        scale={sphereProps.Sphere01.scale.current}
        onpointerEnter={sphereProps.Sphere01.onHover}
        onpointerLeave={sphereProps.Sphere01.onHoverLeave}
        onclick={sphereProps.Sphere01.onClick}
      />
      <T.Mesh
        name="Sphere02"
        geometry={gltf.nodes.Sphere02.geometry}
        material={gltf.materials.Wireframe}
        position={[0, 1, 0]}
        scale={sphereProps.Sphere02.scale.current}
        onpointerEnter={sphereProps.Sphere02.onHover}
        onpointerLeave={sphereProps.Sphere02.onHoverLeave}
        onclick={sphereProps.Sphere02.onClick}
      />
      <T.Mesh
        name="Sphere03"
        geometry={gltf.nodes.Sphere03.geometry}
        material={gltf.materials.Wireframe}
        position={[0, 1, 0]}
        scale={sphereProps.Sphere03.scale.current}
        onpointerEnter={sphereProps.Sphere03.onHover}
        onpointerLeave={sphereProps.Sphere03.onHoverLeave}
        onclick={sphereProps.Sphere03.onClick}
      />
      <T.Mesh
        name="Sphere04"
        geometry={gltf.nodes.Sphere04.geometry}
        material={gltf.materials.Wireframe}
        position={[0, 1, 0]}
        scale={sphereProps.Sphere04.scale.current}
        onpointerEnter={sphereProps.Sphere04.onHover}
        onpointerLeave={sphereProps.Sphere04.onHoverLeave}
        onclick={sphereProps.Sphere04.onClick}
      />
      <T.Mesh
        name="Sphere05"
        geometry={gltf.nodes.Sphere05.geometry}
        material={gltf.materials.Wireframe}
        position={[0, 1, 0]}
        scale={sphereProps.Sphere05.scale.current}
        onpointerEnter={sphereProps.Sphere05.onHover}
        onpointerLeave={sphereProps.Sphere05.onHoverLeave}
        onclick={sphereProps.Sphere05.onClick}
      />
      <T.Mesh
        name="Sphere06"
        geometry={gltf.nodes.Sphere06.geometry}
        material={gltf.materials.Wireframe}
        position={[0, 1, 0]}
        scale={sphereProps.Sphere06.scale.current}
        onpointerEnter={sphereProps.Sphere06.onHover}
        onpointerLeave={sphereProps.Sphere06.onHoverLeave}
        onclick={sphereProps.Sphere06.onClick}
      />
      <T.Mesh
        name="Sphere07"
        geometry={gltf.nodes.Sphere07.geometry}
        material={gltf.materials.Wireframe}
        position={[0, 1, 0]}
        scale={sphereProps.Sphere07.scale.current}
        onpointerEnter={sphereProps.Sphere07.onHover}
        onpointerLeave={sphereProps.Sphere07.onHoverLeave}
        onclick={sphereProps.Sphere07.onClick}
      />
      <T.Mesh
        name="Plane"
        geometry={gltf.nodes.Plane.geometry}
        material={gltf.materials.Floor}
        scale={58.28}
      />
      <T.Mesh
        name="Torus01"
        geometry={gltf.nodes.Torus01.geometry}
        material={gltf.materials.lightring}
        position={[0, 0.01, 0]}
        scale={0.96}
      />
      <T.Mesh
        name="Torus02"
        geometry={gltf.nodes.Torus02.geometry}
        material={gltf.materials['lightring.002']}
        position={[0, 0.01, 0]}
        scale={0.96}
      />
      <T.Mesh
        name="Torus03"
        geometry={gltf.nodes.Torus03.geometry}
        material={gltf.materials['lightring.003']}
        position={[0, 0.01, 0]}
        scale={0.96}
      />
      <T.Mesh
        name="Torus04"
        geometry={gltf.nodes.Torus04.geometry}
        material={gltf.materials['lightring.004']}
        position={[0, 0.01, 0]}
        scale={0.96}
      />
      <T.Mesh
        name="Torus05"
        geometry={gltf.nodes.Torus05.geometry}
        material={gltf.materials['lightring.006']}
        position={[0, 0.01, 0]}
        scale={0.96}
      />
      <T.Mesh
        name="Torus06"
        geometry={gltf.nodes.Torus06.geometry}
        material={gltf.materials['lightring.007']}
        position={[0, 0.01, 0]}
        scale={0.96}
      />
      <T.Mesh
        name="Torus07"
        geometry={gltf.nodes.Torus07.geometry}
        material={gltf.materials['lightring.008']}
        position={[0, 0.01, 0]}
        scale={0.96}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
