<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 src/lib/assets/gltf/site-animation.glb -o src/lib/assets/gltf/site-animation
-->

<script>
  import { Group } from 'three'

  import { T } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  ref = new Group()

  const gltf = useGltf('/src/lib/assets/gltf/site-animation.glb')

  export const { actions, mixer } = useGltfAnimations(gltf, ref)
</script>

<T
  is={ref}
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Scene">
      <T.OrthographicCamera
        name="Camera"
        makeDefault={false}
        far={100}
        near={0.1}
        position={[7.07, 1, 7.06]}
        rotation={[0, Math.PI / 4, 0]}
      />
      <T.DirectionalLight
        name="Sun"
        intensity={683}
        decay={2}
        position={[0, 21.62, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <T.Group position={[0, 0, -1]} />
      </T.DirectionalLight>
      <T.Mesh
        name="Sphere01"
        geometry={gltf.nodes.Sphere01.geometry}
        material={gltf.materials.Wireframe}
        position={[0, 1, 0]}
      />
      <T.Mesh
        name="Sphere02"
        geometry={gltf.nodes.Sphere02.geometry}
        material={gltf.materials.Wireframe}
        position={[0, 1, 0]}
      />
      <T.Mesh
        name="Sphere03"
        geometry={gltf.nodes.Sphere03.geometry}
        material={gltf.materials.Wireframe}
        position={[0, 1, 0]}
      />
      <T.Mesh
        name="Sphere04"
        geometry={gltf.nodes.Sphere04.geometry}
        material={gltf.materials.Wireframe}
        position={[0, 1, 0]}
      />
      <T.Mesh
        name="Sphere05"
        geometry={gltf.nodes.Sphere05.geometry}
        material={gltf.materials.Wireframe}
        position={[0, 1, 0]}
      />
      <T.Mesh
        name="Sphere06"
        geometry={gltf.nodes.Sphere06.geometry}
        material={gltf.materials.Wireframe}
        position={[0, 1, 0]}
      />
      <T.Mesh
        name="Sphere07"
        geometry={gltf.nodes.Sphere07.geometry}
        material={gltf.materials.Wireframe}
        position={[0, 1, 0]}
      />
      <T.Mesh
        name="Plane"
        geometry={gltf.nodes.Plane.geometry}
        material={gltf.materials.Floor}
        scale={58.28}
      />
      <T.Mesh
        name="Torus01"
        geometry={gltf.nodes.Torus01.geometry}
        material={gltf.materials.Torus}
        position={[0, 0.01, 0]}
        scale={0.96}
      />
      <T.Mesh
        name="Torus02"
        geometry={gltf.nodes.Torus02.geometry}
        material={gltf.materials.Torus}
        position={[0, 0.01, 0]}
        scale={0.96}
      />
      <T.Mesh
        name="Torus03"
        geometry={gltf.nodes.Torus03.geometry}
        material={gltf.materials.Torus}
        position={[0, 0.01, 0]}
        scale={0.96}
      />
      <T.Mesh
        name="Torus04"
        geometry={gltf.nodes.Torus04.geometry}
        material={gltf.materials.Torus}
        position={[0, 0.01, 0]}
        scale={0.96}
      />
      <T.Mesh
        name="Torus05"
        geometry={gltf.nodes.Torus05.geometry}
        material={gltf.materials.Torus}
        position={[0, 0.01, 0]}
        scale={0.96}
      />
      <T.Mesh
        name="Torus06"
        geometry={gltf.nodes.Torus06.geometry}
        material={gltf.materials.Torus}
        position={[0, 0.01, 0]}
        scale={0.96}
      />
      <T.Mesh
        name="Torus07"
        geometry={gltf.nodes.Torus07.geometry}
        material={gltf.materials.Torus}
        position={[0, 0.01, 0]}
        scale={0.96}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
