// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: cyd-ui

#ifndef _CYD_UI_UI_H
#define _CYD_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

void Flash_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Name_Label;
extern lv_obj_t * ui_HpArc;
extern lv_obj_t * ui_HP_Label;
void ui_event_Reduce_button(lv_event_t * e);
extern lv_obj_t * ui_Reduce_button;
extern lv_obj_t * ui_Reduce_button_label;
void ui_event_Increace_button(lv_event_t * e);
extern lv_obj_t * ui_Increace_button;
extern lv_obj_t * ui_Increase_button_label;
extern lv_obj_t * ui_HP_value;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_SkullImage;
extern lv_obj_t * ui_DangerLabel;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_LoadingBar;
extern lv_obj_t * ui_LoadingLabel;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_564643_png);    // assets/564643.png
LV_IMG_DECLARE(ui_img_694104942);    // assets/cake-slice.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
