// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: cyd-ui

#ifndef _UI_COMP_SKULLIMAGE_H
#define _UI_COMP_SKULLIMAGE_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT skullimage
#define UI_COMP_SKULLIMAGE_SKULLIMAGE 0
#define _UI_COMP_SKULLIMAGE_NUM 1
lv_obj_t * ui_skullimage_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
