// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: cyd-ui

#include "ui.h"

// COMPONENT skullimage

lv_obj_t * ui_skullimage_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_skullimage;
    cui_skullimage = lv_image_create(comp_parent);
    lv_image_set_src(cui_skullimage, &ui_img_564643_png);
    lv_obj_set_width(cui_skullimage, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(cui_skullimage, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_x(cui_skullimage, 0);
    lv_obj_set_y(cui_skullimage, -30);
    lv_obj_set_align(cui_skullimage, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_skullimage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_skullimage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(cui_skullimage, 60);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_SKULLIMAGE_NUM);
    children[UI_COMP_SKULLIMAGE_SKULLIMAGE] = cui_skullimage;
    lv_obj_add_event_cb(cui_skullimage, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_skullimage, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_skullimage_create_hook(cui_skullimage);
    return cui_skullimage;
}

