// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: cyd-ui

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LoadingBar = lv_bar_create(ui_Screen3);
    lv_bar_set_value(ui_LoadingBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_LoadingBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_LoadingBar, 200);
    lv_obj_set_height(ui_LoadingBar, 20);
    lv_obj_set_x(ui_LoadingBar, 0);
    lv_obj_set_y(ui_LoadingBar, 19);
    lv_obj_set_align(ui_LoadingBar, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_LoadingBar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoadingBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_LoadingBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_LoadingBar,
                                                                                                 lv_obj_get_style_pad_right(ui_LoadingBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_LoadingLabel = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LoadingLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LoadingLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LoadingLabel, -1);
    lv_obj_set_y(ui_LoadingLabel, -28);
    lv_obj_set_align(ui_LoadingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LoadingLabel, "Downloading...");
    lv_obj_set_style_text_font(ui_LoadingLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

}
