// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: cyd-ui

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0xE20000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SkullImage = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_SkullImage, &ui_img_564643_png);
    lv_obj_set_width(ui_SkullImage, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_SkullImage, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_x(ui_SkullImage, 0);
    lv_obj_set_y(ui_SkullImage, -30);
    lv_obj_set_align(ui_SkullImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SkullImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SkullImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_SkullImage, 60);

    ui_DangerLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_DangerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DangerLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DangerLabel, 1);
    lv_obj_set_y(ui_DangerLabel, 64);
    lv_obj_set_align(ui_DangerLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DangerLabel, "Danger");
    lv_obj_set_style_text_color(ui_DangerLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DangerLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DangerLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

}
