version: '3.7'

services:
  db:
    container_name: testalice-db
    image: mysql/mysql-server:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testaliceDB
      - MYSQL_USER=Yodi
      - MYSQL_PASSWORD=Tester@123
    volumes:
      - './scripts:/docker-entrypoint-initdb.d'
  phpnyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
 