// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: cyd-ui

#ifndef _CYD_UI_UI_H
#define _CYD_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Name_Label;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_HP_Label;
void ui_event_Reduce_button(lv_event_t * e);
extern lv_obj_t * ui_Reduce_button;
extern lv_obj_t * ui_Reduce_button_label;
void ui_event_Increace_button(lv_event_t * e);
extern lv_obj_t * ui_Increace_button;
extern lv_obj_t * ui_Increase_button_label;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
