// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: cyd-ui

#include "ui.h"

void reduce_hp(lv_event_t * e)
{
	// Your code here
}

void increase_hp(lv_event_t * e)
{
	// Your code here
}
