// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: cyd-interface

#ifndef _CYD_INTERFACE_UI_H
#define _CYD_INTERFACE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_LogoScreen
void ui_LogoScreen_screen_init(void);
extern lv_obj_t * ui_LogoScreen;
// CUSTOM VARIABLES

// SCREEN: ui_DownloadScreen
void ui_DownloadScreen_screen_init(void);
extern lv_obj_t * ui_DownloadScreen;
extern lv_obj_t * ui_DownloadLabel;
extern lv_obj_t * ui_DownloadBar;
// CUSTOM VARIABLES

// SCREEN: ui_LootScreen
void ui_LootScreen_screen_init(void);
extern lv_obj_t * ui_LootScreen;
extern lv_obj_t * ui_ReceivedLabel;
// CUSTOM VARIABLES

// SCREEN: ui_VirusScreen
void ui_VirusScreen_screen_init(void);
extern lv_obj_t * ui_VirusScreen;
extern lv_obj_t * ui_DangerLabel;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
