// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: cyd-interface

#ifndef _UI_COMP_HEADER_H
#define _UI_COMP_HEADER_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Header
#define UI_COMP_HEADER_HEADER 0
#define UI_COMP_HEADER_TIMELABEL 1
#define UI_COMP_HEADER_WIFIIMAGE 2
#define UI_COMP_HEADER_BATERYIMAGE 3
#define UI_COMP_HEADER_NAMELABEL 4
#define UI_COMP_HEADER_HOMEIMAGE 5
#define _UI_COMP_HEADER_NUM 6
lv_obj_t * ui_Header_create(lv_obj_t * comp_parent);
void ui_event_comp_Header_HomeImage(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
