// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: cyd-interface

#include "ui.h"

void ui_event_comp_Header_HomeImage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_Header = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Home_screen_init);
    }
}

// COMPONENT Header

lv_obj_t * ui_Header_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Header;
    cui_Header = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Header);
    lv_obj_set_width(cui_Header, 320);
    lv_obj_set_height(cui_Header, 24);
    lv_obj_set_x(cui_Header, -1);
    lv_obj_set_y(cui_Header, -107);
    lv_obj_set_align(cui_Header, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Header, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Header, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_TimeLabel;
    cui_TimeLabel = lv_label_create(cui_Header);
    lv_obj_set_width(cui_TimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_TimeLabel, 140);
    lv_obj_set_y(cui_TimeLabel, lv_pct(0));
    lv_obj_set_align(cui_TimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_TimeLabel, "10:45");

    lv_obj_t * cui_WifiImage;
    cui_WifiImage = lv_image_create(cui_Header);
    lv_image_set_src(cui_WifiImage, &ui_img_wifi_png);
    lv_obj_set_width(cui_WifiImage, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(cui_WifiImage, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(cui_WifiImage, 75);
    lv_obj_set_y(cui_WifiImage, 0);
    lv_obj_set_align(cui_WifiImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_WifiImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_WifiImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(cui_WifiImage, 120);

    lv_obj_t * cui_BateryImage;
    cui_BateryImage = lv_image_create(cui_Header);
    lv_image_set_src(cui_BateryImage, &ui_img_53718616);
    lv_obj_set_width(cui_BateryImage, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(cui_BateryImage, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(cui_BateryImage, 105);
    lv_obj_set_y(cui_BateryImage, 0);
    lv_obj_set_align(cui_BateryImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_BateryImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_BateryImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(cui_BateryImage, 120);

    lv_obj_t * cui_NameLabel;
    cui_NameLabel = lv_label_create(cui_Header);
    lv_obj_set_width(cui_NameLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_NameLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_NameLabel, 40);
    lv_obj_set_y(cui_NameLabel, 0);
    lv_obj_set_align(cui_NameLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_NameLabel, "Name");
    lv_obj_set_style_text_align(cui_NameLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_HomeImage;
    cui_HomeImage = lv_image_create(cui_Header);
    lv_image_set_src(cui_HomeImage, &ui_img_house_sm_png);
    lv_obj_set_width(cui_HomeImage, 22);
    lv_obj_set_height(cui_HomeImage, 22);
    lv_obj_set_x(cui_HomeImage, -144);
    lv_obj_set_y(cui_HomeImage, 0);
    lv_obj_set_align(cui_HomeImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_HomeImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_HomeImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_HEADER_NUM);
    children[UI_COMP_HEADER_HEADER] = cui_Header;
    children[UI_COMP_HEADER_TIMELABEL] = cui_TimeLabel;
    children[UI_COMP_HEADER_WIFIIMAGE] = cui_WifiImage;
    children[UI_COMP_HEADER_BATERYIMAGE] = cui_BateryImage;
    children[UI_COMP_HEADER_NAMELABEL] = cui_NameLabel;
    children[UI_COMP_HEADER_HOMEIMAGE] = cui_HomeImage;
    lv_obj_add_event_cb(cui_Header, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Header, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_HomeImage, ui_event_comp_Header_HomeImage, LV_EVENT_ALL, children);
    ui_comp_Header_create_hook(cui_Header);
    return cui_Header;
}

