// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: cyd-interface

#include "ui.h"

void ui_DownloadScreen_screen_init(void)
{
    ui_DownloadScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_DownloadScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DownloadScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DownloadScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DownloadLabel = lv_label_create(ui_DownloadScreen);
    lv_obj_set_width(ui_DownloadLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DownloadLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DownloadLabel, 0);
    lv_obj_set_y(ui_DownloadLabel, -30);
    lv_obj_set_align(ui_DownloadLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DownloadLabel, "Downloading ...");

    ui_DownloadBar = lv_bar_create(ui_DownloadScreen);
    lv_bar_set_value(ui_DownloadBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_DownloadBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_DownloadBar, 265);
    lv_obj_set_height(ui_DownloadBar, 10);
    lv_obj_set_x(ui_DownloadBar, 0);
    lv_obj_set_y(ui_DownloadBar, -1);
    lv_obj_set_align(ui_DownloadBar, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_DownloadBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_DownloadBar,
                                                                                                  lv_obj_get_style_pad_right(ui_DownloadBar, LV_PART_MAIN) + 1, LV_PART_MAIN);

}
