// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: cyd-ui

#include "ui.h"
#include "../character.h"

void reduce_hp(lv_event_t * e)
{
	if(currentCharacter.currentHp == 0) {
		return;
	}
	currentCharacter.currentHp = currentCharacter.currentHp -1;
	Serial.println("reduce hp");
	Serial.println(String(currentCharacter.currentHp).c_str());

}

void increase_hp(lv_event_t * e)
{
	if(currentCharacter.currentHp == currentCharacter.maxHp) {
		return;
	}
	currentCharacter.currentHp = currentCharacter.currentHp + 1;
	Serial.println("increase hp");
	Serial.println(String(currentCharacter.currentHp).c_str());

}
