// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: cyd-interface

#include "ui.h"

void ui_Implants_screen_init(void)
{
    ui_Implants = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Implants, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Header2 = lv_obj_create(ui_Implants);
    lv_obj_remove_style_all(ui_Header2);
    lv_obj_set_width(ui_Header2, 320);
    lv_obj_set_height(ui_Header2, 24);
    lv_obj_set_x(ui_Header2, -1);
    lv_obj_set_y(ui_Header2, -107);
    lv_obj_set_align(ui_Header2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Header2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Header2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Header2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel2 = lv_label_create(ui_Header2);
    lv_obj_set_width(ui_TimeLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabel2, 140);
    lv_obj_set_y(ui_TimeLabel2, lv_pct(0));
    lv_obj_set_align(ui_TimeLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabel2, "10:45");

    ui_WifiImage2 = lv_image_create(ui_Header2);
    lv_image_set_src(ui_WifiImage2, &ui_img_wifi_png);
    lv_obj_set_width(ui_WifiImage2, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_WifiImage2, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_WifiImage2, 75);
    lv_obj_set_y(ui_WifiImage2, 0);
    lv_obj_set_align(ui_WifiImage2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiImage2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WifiImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_WifiImage2, 120);

    ui_BateryImage2 = lv_image_create(ui_Header2);
    lv_image_set_src(ui_BateryImage2, &ui_img_53718616);
    lv_obj_set_width(ui_BateryImage2, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_BateryImage2, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_BateryImage2, 105);
    lv_obj_set_y(ui_BateryImage2, 0);
    lv_obj_set_align(ui_BateryImage2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BateryImage2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BateryImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_BateryImage2, 120);

    ui_NameLabel2 = lv_label_create(ui_Header2);
    lv_obj_set_width(ui_NameLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NameLabel2, 40);
    lv_obj_set_y(ui_NameLabel2, 0);
    lv_obj_set_align(ui_NameLabel2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NameLabel2, "Name");
    lv_obj_set_style_text_align(ui_NameLabel2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButton2 = lv_imagebutton_create(ui_Header2);
    lv_imagebutton_set_src(ui_HomeButton2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_house_sm_png, NULL);
    lv_obj_set_width(ui_HomeButton2, 22);
    lv_obj_set_height(ui_HomeButton2, 22);
    lv_obj_set_x(ui_HomeButton2, -144);
    lv_obj_set_y(ui_HomeButton2, 0);
    lv_obj_set_align(ui_HomeButton2, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_HomeButton2, ui_event_HomeButton2, LV_EVENT_ALL, NULL);

}
