// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: cyd-interface

#include "ui.h"

void ui_Items_screen_init(void)
{
    ui_Items = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Items, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Header2 = ui_Header_create(ui_Items);
    lv_obj_set_x(ui_Header2, -1);
    lv_obj_set_y(ui_Header2, -107);

    ui_ItemsTitle = lv_label_create(ui_Items);
    lv_obj_set_width(ui_ItemsTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ItemsTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ItemsTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ItemsTitle, "Items");

}
