// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: cyd-interface

#include "ui.h"

void ui_Implants_screen_init(void)
{
    ui_Implants = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Implants, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Header3 = ui_Header_create(ui_Implants);
    lv_obj_set_x(ui_Header3, -1);
    lv_obj_set_y(ui_Header3, -107);

    ui_ImplantsTitle = lv_label_create(ui_Implants);
    lv_obj_set_width(ui_ImplantsTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImplantsTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImplantsTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ImplantsTitle, "Implants");

}
