// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: cyd-interface

#include "ui.h"

void ui_Items_screen_init(void)
{
    ui_Items = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Items, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Header4 = lv_obj_create(ui_Items);
    lv_obj_remove_style_all(ui_Header4);
    lv_obj_set_width(ui_Header4, 320);
    lv_obj_set_height(ui_Header4, 24);
    lv_obj_set_x(ui_Header4, -1);
    lv_obj_set_y(ui_Header4, -107);
    lv_obj_set_align(ui_Header4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Header4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Header4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Header4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel4 = lv_label_create(ui_Header4);
    lv_obj_set_width(ui_TimeLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabel4, 140);
    lv_obj_set_y(ui_TimeLabel4, lv_pct(0));
    lv_obj_set_align(ui_TimeLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabel4, "10:45");

    ui_WifiImage4 = lv_image_create(ui_Header4);
    lv_image_set_src(ui_WifiImage4, &ui_img_wifi_png);
    lv_obj_set_width(ui_WifiImage4, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_WifiImage4, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_WifiImage4, 75);
    lv_obj_set_y(ui_WifiImage4, 0);
    lv_obj_set_align(ui_WifiImage4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiImage4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WifiImage4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_WifiImage4, 120);

    ui_BateryImage4 = lv_image_create(ui_Header4);
    lv_image_set_src(ui_BateryImage4, &ui_img_53718616);
    lv_obj_set_width(ui_BateryImage4, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_BateryImage4, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_BateryImage4, 105);
    lv_obj_set_y(ui_BateryImage4, 0);
    lv_obj_set_align(ui_BateryImage4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BateryImage4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BateryImage4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_BateryImage4, 120);

    ui_NameLabel4 = lv_label_create(ui_Header4);
    lv_obj_set_width(ui_NameLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NameLabel4, 40);
    lv_obj_set_y(ui_NameLabel4, 0);
    lv_obj_set_align(ui_NameLabel4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NameLabel4, "Name");
    lv_obj_set_style_text_align(ui_NameLabel4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButton4 = lv_imagebutton_create(ui_Header4);
    lv_imagebutton_set_src(ui_HomeButton4, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_house_sm_png, NULL);
    lv_obj_set_width(ui_HomeButton4, 22);
    lv_obj_set_height(ui_HomeButton4, 22);
    lv_obj_set_x(ui_HomeButton4, -144);
    lv_obj_set_y(ui_HomeButton4, 0);
    lv_obj_set_align(ui_HomeButton4, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_HomeButton4, ui_event_HomeButton4, LV_EVENT_ALL, NULL);

}
