// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: cyd-interface

#include "ui.h"

void ui_LootScreen_screen_init(void)
{
    ui_LootScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_LootScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LootScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LootScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReceivedLabel = lv_label_create(ui_LootScreen);
    lv_obj_set_width(ui_ReceivedLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReceivedLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ReceivedLabel, 0);
    lv_obj_set_y(ui_ReceivedLabel, -58);
    lv_obj_set_align(ui_ReceivedLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ReceivedLabel, "Verkregen");

}
