// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: cyd-interface

#include "ui.h"

void ui_LogoScreen_screen_init(void)
{
    ui_LogoScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_LogoScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
