// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: cyd-interface

#include "ui.h"

void ui_Messages_screen_init(void)
{
    ui_Messages = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Messages, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Header5 = lv_obj_create(ui_Messages);
    lv_obj_remove_style_all(ui_Header5);
    lv_obj_set_width(ui_Header5, 320);
    lv_obj_set_height(ui_Header5, 24);
    lv_obj_set_x(ui_Header5, -1);
    lv_obj_set_y(ui_Header5, -107);
    lv_obj_set_align(ui_Header5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Header5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Header5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Header5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel5 = lv_label_create(ui_Header5);
    lv_obj_set_width(ui_TimeLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabel5, 140);
    lv_obj_set_y(ui_TimeLabel5, lv_pct(0));
    lv_obj_set_align(ui_TimeLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabel5, "10:45");

    ui_WifiImage5 = lv_image_create(ui_Header5);
    lv_image_set_src(ui_WifiImage5, &ui_img_wifi_png);
    lv_obj_set_width(ui_WifiImage5, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_WifiImage5, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_WifiImage5, 75);
    lv_obj_set_y(ui_WifiImage5, 0);
    lv_obj_set_align(ui_WifiImage5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiImage5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WifiImage5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_WifiImage5, 120);

    ui_BateryImage5 = lv_image_create(ui_Header5);
    lv_image_set_src(ui_BateryImage5, &ui_img_53718616);
    lv_obj_set_width(ui_BateryImage5, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_BateryImage5, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_BateryImage5, 105);
    lv_obj_set_y(ui_BateryImage5, 0);
    lv_obj_set_align(ui_BateryImage5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BateryImage5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BateryImage5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_BateryImage5, 120);

    ui_NameLabel5 = lv_label_create(ui_Header5);
    lv_obj_set_width(ui_NameLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NameLabel5, 40);
    lv_obj_set_y(ui_NameLabel5, 0);
    lv_obj_set_align(ui_NameLabel5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NameLabel5, "Name");
    lv_obj_set_style_text_align(ui_NameLabel5, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButton5 = lv_imagebutton_create(ui_Header5);
    lv_imagebutton_set_src(ui_HomeButton5, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_house_sm_png, NULL);
    lv_obj_set_width(ui_HomeButton5, 22);
    lv_obj_set_height(ui_HomeButton5, 22);
    lv_obj_set_x(ui_HomeButton5, -144);
    lv_obj_set_y(ui_HomeButton5, 0);
    lv_obj_set_align(ui_HomeButton5, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_HomeButton5, ui_event_HomeButton5, LV_EVENT_ALL, NULL);

}
