// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: cyd-interface

#include "ui.h"

void ui_Messages_screen_init(void)
{
    ui_Messages = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Messages, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Header1 = ui_Header_create(ui_Messages);
    lv_obj_set_x(ui_Header1, -1);
    lv_obj_set_y(ui_Header1, -107);

    ui_MessagesTitle = lv_label_create(ui_Messages);
    lv_obj_set_width(ui_MessagesTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MessagesTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MessagesTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MessagesTitle, "Messages");

}
