// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: cyd-ui

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Name_Label = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Name_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Name_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Name_Label, 0);
    lv_obj_set_y(ui_Name_Label, -100);
    lv_obj_set_align(ui_Name_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Name_Label, "{name}");

    ui_Arc1 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Arc1, 150);
    lv_obj_set_height(ui_Arc1, 150);
    lv_obj_set_x(ui_Arc1, 0);
    lv_obj_set_y(ui_Arc1, -1);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Arc1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_Arc1, 50);

    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_HP_Label = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_HP_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HP_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HP_Label, 0);
    lv_obj_set_y(ui_HP_Label, 60);
    lv_obj_set_align(ui_HP_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HP_Label, "HP");

    ui_Reduce_button = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Reduce_button, 33);
    lv_obj_set_height(ui_Reduce_button, 148);
    lv_obj_set_x(ui_Reduce_button, -115);
    lv_obj_set_y(ui_Reduce_button, -6);
    lv_obj_set_align(ui_Reduce_button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Reduce_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Reduce_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Reduce_button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Reduce_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Reduce_button, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Reduce_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Reduce_button, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Reduce_button_label = lv_label_create(ui_Reduce_button);
    lv_obj_set_width(ui_Reduce_button_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Reduce_button_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Reduce_button_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Reduce_button_label, "-");

    ui_Increace_button = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Increace_button, 33);
    lv_obj_set_height(ui_Increace_button, 148);
    lv_obj_set_x(ui_Increace_button, 114);
    lv_obj_set_y(ui_Increace_button, -5);
    lv_obj_set_align(ui_Increace_button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Increace_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Increace_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Increace_button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Increace_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Increace_button, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Increace_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Increace_button, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Increase_button_label = lv_label_create(ui_Increace_button);
    lv_obj_set_width(ui_Increase_button_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Increase_button_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Increase_button_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Increase_button_label, "+");

    ui_HP_value = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_HP_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HP_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HP_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HP_value, "text");
    lv_obj_set_style_text_font(ui_HP_value, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Reduce_button, ui_event_Reduce_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Increace_button, ui_event_Increace_button, LV_EVENT_ALL, NULL);

}
