// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: cyd-interface

#include "ui.h"

void ui_VirusScreen_screen_init(void)
{
    ui_VirusScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_VirusScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_VirusScreen, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VirusScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VirusImage = lv_image_create(ui_VirusScreen);
    lv_image_set_src(ui_VirusImage, &ui_img_virus_png);
    lv_obj_set_width(ui_VirusImage, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_VirusImage, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_x(ui_VirusImage, 0);
    lv_obj_set_y(ui_VirusImage, -44);
    lv_obj_set_align(ui_VirusImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VirusImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_VirusImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_VirusImage, 50);

    ui_DangerLabel = lv_label_create(ui_VirusScreen);
    lv_obj_set_width(ui_DangerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DangerLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DangerLabel, 5);
    lv_obj_set_y(ui_DangerLabel, 41);
    lv_obj_set_align(ui_DangerLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DangerLabel, "Danger!!!");
    lv_obj_set_style_text_color(ui_DangerLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DangerLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
